name: MLOps Pipeline (FastAPI + EKS + ECR)

on:
  push:
    branches:
      - main
      - master

  pull_request:

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:

      # =========================
      # CODE CHECKOUT
      # =========================
      - name: Checkout code
        uses: actions/checkout@v3

      # =========================
      # PYTHON SETUP
      # =========================
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # =========================
      # CACHE PIP
      # =========================
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      # =========================
      # INSTALL DEPENDENCIES
      # =========================
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[s3]==3.48.3
          pip install "pathspec<0.12.0"

      # =========================
      # AWS AUTH
      # =========================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # =========================
      # VERIFY AWS
      # =========================
      - name: Verify AWS identity
        run: aws sts get-caller-identity

      # =========================
      # ENV VARIABLES
      # =========================
      - name: Set environment variables
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV
          echo "REPO_OWNER=chabdullah7" >> $GITHUB_ENV
          echo "REPO_NAME=Sentiment_Analysis" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/chabdullah7/Sentiment_Analysis.mlflow" >> $GITHUB_ENV

      # =========================
      # DVC PIPELINE
      # =========================
      - name: Run DVC pipeline
        run: dvc repro

      # =========================
      # TESTS
      # =========================
      - name: Run tests
        run: python -m unittest discover -s tests -p "test_*.py"

      # =========================
      # MODEL PROMOTION
      # =========================
      - name: Promote model
        if: success()
        run: python scripts/promote_model.py

      # =========================
      # LOGIN TO ECR
      # =========================
      - name: Login to AWS ECR
        if: success()
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # =========================
      # BUILD IMAGE
      # =========================
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

      # =========================
      # TAG IMAGE
      # =========================
      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # =========================
      # PUSH IMAGE
      # =========================
      - name: Push Docker image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # =========================
      # SETUP KUBECTL
      # =========================
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      # =========================
      # CONNECT EKS
      # =========================
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name fastapi-app-cluster

      # =========================
      # VERIFY CLUSTER
      # =========================
      - name: Verify cluster
        run: |
          kubectl get nodes
          kubectl get pods

      # =========================
      # KUBERNETES SECRET
      # =========================
      - name: Create Kubernetes Secret
        run: |
          kubectl create secret generic app-secret \
            --from-literal=DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }} \
            --from-literal=MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }} \
            --dry-run=client -o yaml | kubectl apply -f -

      # =========================
      # DEPLOY TO EKS
      # =========================
      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl get svc

      # =========================
      # FINAL CHECK
      # =========================
      - name: Verify Docker
        run: docker info