name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc dvc[s3]

      # =========================
      # Run DVC Pipeline
      # =========================
      - name: Run DVC Pipeline
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc repro

      # =========================
      # Run FastAPI Tests
      # =========================
      - name: Run FastAPI tests
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          REPO_OWNER: chabdullah7
          REPO_NAME: Sentiment_Analysis
          MLFLOW_TRACKING_URI: https://dagshub.com/chabdullah7/Sentiment_Analysis.mlflow
        run: |
          python -m unittest tests/test_fastapi_app.py

      # =========================
      # Promote Model
      # =========================
      - name: Promote model to production
        if: success()
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          REPO_OWNER: chabdullah7
          REPO_NAME: Sentiment_Analysis
          MLFLOW_TRACKING_URI: https://dagshub.com/chabdullah7/Sentiment_Analysis.mlflow
        run: |
          python scripts/promote_model.py